dist: trusty
sudo: required
services:
- docker
language: go
go:
- 1.11.x
addons:
  apt:
    packages:
    - rpm
    - snapd
env:
  global:
  - GO111MODULE="on"
  - PATH=/snap/bin:$PATH
  - secure: RSXMNFZ9gF0tDTmpj7lNPTcJKixK06G+KIHdHlXbjv/kUQboLLLHXSVJoIUaWiy7vSURuougsXkxgTT1ISEMj+0vpkEzlJEWVxzPqUSXMYsepSsFs6nUdDin8oywliqnw3aYCXqRof60CKrLBjkINWg73NGNp9qx1/8dfGLU50b4HlHOSE19xbrjiVrPPIVY7IT3t/He9P05yKQ7n0d6LA9t4WSofpOrrfuNZy+ZTwJWzPUwujCPkErOOaXPBWfM+DsQGNuzfdImE38jONnHXASpVyhJYtQeU26sjlyzs1uPr9gfXCCf7Sc2YHJE0wa5OLalh3CB6xyKUnWe1P3Y64EfryfFRzEX2aSyeXf8bO1oG0QyamBOblteKbL0rRLBgmihUHCPz1rJXhlMMAD6fAfuVE/iVW10BiNdDUh7dlbHjc5BHG/UNrxZwuI6YztSllmYApRzx6B5M9yS09Ab9L+WT9hsZo9uAe3mqvWgVfDjLgW+XC8VZQqRJxdaxXpBD8F/bKWxUXEh/tUtoFqR+QGewaGSyqPxZ0AAVHQ//pqf0iFNfk4yaguvUsjCgrN2byfosbHAw2QqJAQbYMmgAj/yMepPygM8rJoOsxg6ZcEUguftbJR66GEFWwwN73AlX3gQ1uHBQzi9NUhH98PTrhonuWtc/53srZk1UtxGWT0=
install:
- go install
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
- sudo snap install snapcraft --classic
script:
- go test -v -covermode=count -coverprofile=coverage.out
- "$HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken
  $COVERALLS_TOKEN"
branches:
  only:
  - master
  - /v\d+\.\d+(\-[a-z])?/
matrix:
  fast_finish: true
  allow_failures:
  - go: tip

before_install:
- openssl aes-256-cbc -K $encrypted_822d5ce59246_key -iv $encrypted_822d5ce59246_iv
  -in scripts/secrets.tar.gz.enc -out scripts/secrets.tar.gz -d
- tar -zxf scripts/secrets.tar.gz
- bash secrets/getgocookie.sh

after_success:
- test -n "$TRAVIS_TAG" && snapcraft login --with secrets/snap.login

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
dd:

